name: Android-Чтосмотреть-福利
on:
  workflow_dispatch:
  schedule:
    - cron: '55 21 * * *'
  watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        zq_cookie: ${{ secrets.ZQ_COOKIE }}
        zq_cookie2: ${{ secrets.ZQ_COOKIE2 }}
        zq_cookie3: ${{ secrets.ZQ_COOKIE3 }}
        zq_cookie4: ${{ secrets.ZQ_COOKIE4 }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【Android-Чтосмотреть-Rifah】'
        if: env.zq_cookie
        run: |
          node Android-Чтосмотреть-Rifah.js
        env:
          zq_cookie: ${{ secrets.ZQ_COOKIE }} ${{ secrets.ZQ_COOKIE2 }}

      - name: '运行 【Android-Чтосмотреть-Rifah二】'
        if: env.YOUTH_READ2
        run: |
          node Task/Youth_Read.js
        env:
          zqlookStartbody: ${{ secrets.ZQLOOKSTARTBODY2 }}
          zq_cookie: ${{ secrets.ZQ_COOKIE2 }}

      - name: '运行 【Android-Чтосмотреть-Rifah三】'
        if: env.YOUTH_READ3
        run: |
          node Task/Youth_Read.js
        env:
          zqlookStartbody: ${{ secrets.ZQLOOKSTARTBODY3 }}
          zq_cookie: ${{ secrets.ZQ_COOKIE3 }}

      - name: '运行 【Android-Чтосмотреть-Rifah四】'
        if: env.YOUTH_READ4
        run: |
          node Task/Youth_Read.js
        env:
          zqlookStartbody: ${{ secrets.ZQLOOKSTARTBODY4 }}
          zq_cookie: ${{ secrets.ZQ_COOKIE4 }}
