name: Android-Чтосмотреть-阅读奖励领取
on:
  workflow_dispatch:
  schedule:
    - cron: 1 11 * * *
  watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【zq_5_60】'
        run: |
          
          node zq_5_60.js
        env:
          zqerciboxbody: ${{ secrets.zqerciboxbody }}
